export const portfolioConfig = {
  personal: {
    name: "Ron Marvin De Jesus",
    title: "Full Stack Developer",
    bio: "Passionate developer with 2+ years of experience building modern web applications. I love creating efficient, scalable solutions and learning new technologies.",
    email: "ronmarvin.dejesus@gmail.com",
    github: "https://github.com/lc-vinchii",
    linkedin: "https://linkedin.com/in/alexjohnson",
    location: "Bulacan, Philippines",
  },

  techStack: [
  {
    name: "JavaScript",
    category: "Language",
    level: "Expert",
    icon: "📜",
    description: "Dynamic scripting for interactive web applications",
  },
  {
    name: "jQuery",
    category: "Frontend",
    level: "Intermediate",
    icon: "🌀",
    description: "Simplified DOM manipulation and AJAX handling",
  },
  {
    name: "Bootstrap",
    category: "Frontend",
    level: "Intermediate",
    icon: "🎨",
    description: "Responsive CSS framework for layout and components",
  },
  {
    name: "React",
    category: "Frontend",
    level: "Expert",
    icon: "⚛️",
    description: "Component-based UI library using hooks and context",
  },
  {
    name: "CSS",
    category: "Frontend",
    level: "Advanced",
    icon: "🎨",
    description: "Styling and layout for responsive design",
  },
  {
    name: "Tailwind",
    category: "Frontend",
    level: "Advanced",
    icon: "🌬️",
    description: "Utility-first CSS framework for rapid UI development",
  },
  {
    name: "PHP",
    category: "Language",
    level: "Intermediate",
    icon: "🐘",
    description: "Server-side scripting for dynamic websites",
  },
  {
    name: "Yii2",
    category: "Backend Framework",
    level: "Intermediate",
    icon: "⚙️",
    description: "High-performance PHP framework for web applications",
  },
  {
    name: "Laravel",
    category: "Backend Framework",
    level: "Advanced",
    icon: "🚀",
    description: "Elegant PHP framework with expressive syntax",
  },
  {
    name: "TypeScript",
    category: "Language",
    level: "Advanced",
    icon: "📘",
    description: "Typed superset of JavaScript for large-scale apps",
  },
  {
    name: "Node.js",
    category: "Backend",
    level: "Advanced",
    icon: "🟢",
    description: "Server-side JavaScript runtime for scalable applications",
  },
  {
    name: "Next.js",
    category: "Framework",
    level: "Advanced",
    icon: "▲",
    description: "Full-stack React framework for SSR and API routes",
  },
  {
    name: "Electron",
    category: "Desktop",
    level: "Intermediate",
    icon: "🖥️",
    description: "Build cross-platform desktop apps using web tech",
  },
  {
    name: "Python",
    category: "Language",
    level: "Advanced",
    icon: "🐍",
    description: "Versatile language for scripting, automation, and ML",
  },
  {
    name: "Java",
    category: "Language",
    level: "Intermediate",
    icon: "☕",
    description: "Object-oriented language for cross-platform development",
  },
  {
    name: "C++",
    category: "Language",
    level: "Intermediate",
    icon: "💻",
    description: "High-performance programming for system-level software",
  },
  {
    name: "Playwright",
    category: "Testing",
    level: "Intermediate",
    icon: "🎭",
    description: "E2E browser testing with fast and reliable automation",
  },
  {
    name: "Selenium",
    category: "Testing",
    level: "Intermediate",
    icon: "🧪",
    description: "Cross-browser automation for web applications",
  },
  {
    name: "JMeter",
    category: "Testing",
    level: "Intermediate",
    icon: "📈",
    description: "Load testing and performance analysis for applications",
  },
  {
    name: "OWASP ZAP",
    category: "Security",
    level: "Intermediate",
    icon: "🛡️",
    description: "Web app security scanner for detecting vulnerabilities",
  },
  {
    name: "SQL",
    category: "Database",
    level: "Advanced",
    icon: "🗄️",
    description: "Structured query language for managing relational databases",
  },
  {
    name: "AWS",
    category: "Cloud",
    level: "Intermediate",
    icon: "☁️",
    description: "Scalable cloud services for computing, storage, and deployment",
  },
  {
    name: "DigitalOcean",
    category: "Cloud",
    level: "Intermediate",
    icon: "🌐",
    description: "Cloud infrastructure provider for simplified deployments",
  },
  ],

  projects: [
    {
      id: 1,
      title: "E-Commerce Platform",
      description:
        "A full-stack e-commerce solution with payment integration, inventory management, and admin dashboard.",
      longDescription:
        "Built a comprehensive e-commerce platform from scratch using Next.js and PostgreSQL. Features include user authentication, product catalog, shopping cart, payment processing with Stripe, order management, and an admin dashboard for inventory control.",
      image: "/placeholder.svg?height=300&width=500",
      techStack: ["Next.js", "TypeScript", "PostgreSQL", "Stripe", "Tailwind CSS"],
      liveUrl: "https://ecommerce-demo.vercel.app",
      githubUrl: "https://github.com/alexjohnson/ecommerce-platform",
      featured: true,
    },
    {
      id: 2,
      title: "Task Management App",
      description:
        "A collaborative task management application with real-time updates and team collaboration features.",
      longDescription:
        "Developed a real-time task management application using React and Socket.io. The app supports team collaboration, drag-and-drop task organization, real-time notifications, and progress tracking with beautiful data visualizations.",
      image: "/placeholder.svg?height=300&width=500",
      techStack: ["React", "Node.js", "Socket.io", "MongoDB", "Chart.js"],
      liveUrl: "https://taskmanager-demo.vercel.app",
      githubUrl: "https://github.com/alexjohnson/task-manager",
      featured: true,
    },
    {
      id: 3,
      title: "Weather Dashboard",
      description: "A responsive weather dashboard with location-based forecasts and interactive maps.",
      longDescription:
        "Created a comprehensive weather dashboard that provides current conditions, 7-day forecasts, and interactive weather maps. Features location-based weather detection, favorite locations, and detailed weather analytics.",
      image: "/placeholder.svg?height=300&width=500",
      techStack: ["React", "OpenWeather API", "Mapbox", "Chart.js"],
      liveUrl: "https://weather-dashboard-demo.vercel.app",
      githubUrl: "https://github.com/alexjohnson/weather-dashboard",
      featured: false,
    },
    {
      id: 4,
      title: "Blog Platform",
      description: "A modern blog platform with markdown support, SEO optimization, and content management.",
      longDescription:
        "Built a full-featured blog platform with markdown support, syntax highlighting, SEO optimization, and a content management system. Includes features like tags, categories, search functionality, and social sharing.",
      image: "/placeholder.svg?height=300&width=500",
      techStack: ["Next.js", "MDX", "Prisma", "PostgreSQL"],
      liveUrl: "https://blog-platform-demo.vercel.app",
      githubUrl: "https://github.com/alexjohnson/blog-platform",
      featured: false,
    },
  ],
}
