export const portfolioConfig = {
  personal: {
    name: "Ron Marvin De Jesus",
    title: "Full Stack Developer",
    bio: "Passionate developer with 2+ years of experience building modern web applications. I love creating efficient, scalable solutions and learning new technologies.",
    email: "ronmarvin.dejesus@gmail.com",
    github: "https://github.com/lc-vinchii",
    linkedin: "https://linkedin.com/in/alexjohnson",
    location: "Bulacan, Philippines",
  },

  techStack: [
  {
    name: "JavaScript",
    category: "Language",
    level: "Expert",
    icon: "📜",
    description: "Dynamic scripting for interactive web applications",
  },
  {
    name: "jQuery",
    category: "Frontend",
    level: "Expert",
    icon: "🌀",
    description: "Simplified DOM manipulation and AJAX handling",
  },
  {
    name: "Bootstrap",
    category: "Frontend",
    level: "Advanced",
    icon: "🎨",
    description: "Responsive CSS framework for layout and components",
  },
  {
    name: "React",
    category: "Frontend",
    level: "Advanced",
    icon: "⚛️",
    description: "Component-based UI library using hooks and context",
  },
  {
    name: "CSS",
    category: "Frontend",
    level: "Advanced",
    icon: "🎨",
    description: "Styling and layout for responsive design",
  },
  {
    name: "Tailwind",
    category: "Frontend",
    level: "Advanced",
    icon: "🌬️",
    description: "Utility-first CSS framework for rapid UI development",
  },
  {
    name: "PHP",
    category: "Language",
    level: "Expert",
    icon: "🐘",
    description: "Server-side scripting for dynamic websites",
  },
  {
    name: "Yii2",
    category: "Backend Framework",
    level: "Advanced",
    icon: "⚙️",
    description: "High-performance PHP framework for web applications",
  },
  {
    name: "Laravel",
    category: "Backend Framework",
    level: "Advanced",
    icon: "🚀",
    description: "Elegant PHP framework with expressive syntax",
  },
  {
    name: "TypeScript",
    category: "Language",
    level: "Advanced",
    icon: "📘",
    description: "Typed superset of JavaScript for large-scale apps",
  },
  {
    name: "Node.js",
    category: "Backend",
    level: "Expert",
    icon: "🟢",
    description: "Server-side JavaScript runtime for scalable applications",
  },
  {
    name: "Next.js",
    category: "Framework",
    level: "Intermediate",
    icon: "▲",
    description: "Full-stack React framework for SSR and API routes",
  },
  {
    name: "Electron",
    category: "Desktop",
    level: "Advanced",
    icon: "🖥️",
    description: "Build cross-platform desktop apps using web tech",
  },
  {
    name: "Python",
    category: "Language",
    level: "Advanced",
    icon: "🐍",
    description: "Versatile language for scripting, automation, and ML",
  },
  {
    name: "Java",
    category: "Language",
    level: "Intermediate",
    icon: "☕",
    description: "Object-oriented language for cross-platform development",
  },
  {
    name: "C++",
    category: "Language",
    level: "Intermediate",
    icon: "💻",
    description: "High-performance programming for system-level software",
  },
  {
    name: "Playwright",
    category: "Testing",
    level: "Expert",
    icon: "🎭",
    description: "E2E browser testing with fast and reliable automation",
  },
  {
    name: "Selenium",
    category: "Testing",
    level: "Expert",
    icon: "🧪",
    description: "Cross-browser automation for web applications",
  },
  {
    name: "JMeter",
    category: "Testing",
    level: "Advanced",
    icon: "📈",
    description: "Load testing and performance analysis for applications",
  },
  {
    name: "OWASP ZAP",
    category: "Security",
    level: "Intermediate",
    icon: "🛡️",
    description: "Web app security scanner for detecting vulnerabilities",
  },
  {
    name: "SQL",
    category: "Database",
    level: "Expert",
    icon: "🗄️",
    description: "Structured query language for managing relational databases",
  },
  {
    name: "AWS",
    category: "Cloud",
    level: "Advanced",
    icon: "☁️",
    description: "Scalable cloud services for computing, storage, and deployment",
  },
  {
    name: "DigitalOcean",
    category: "Cloud",
    level: "Advanced",
    icon: "🌐",
    description: "Cloud infrastructure provider for simplified deployments",
  },
  ],

  projects: [
    {
      id: 1,
      title: "Client POS System and E-commerce Web Application",
      description:
        "A full-stack e-commerce solution with inventory management, and admin dashboard.",
      longDescription:
        "Designed and developed a web application to facilitate client operations for both POS system and e-commerce platform. Utilized MySQL, PHP, JavaScript, HTML/CSS to develop the web app. Features include user authentication, product catalog, shopping cart, order management, and an admin dashboard for inventory control.",
      image: "/images/projects/preview-1.PNG",
      techStack: ["MySQL", "PHP", "JavaScript", "HTML", "CSS"],
      liveUrl: "https://invsystem.42web.io/",
      githubUrl: "",
      featured: false,
    },
  ],
}
